### ISSUE TITLE
Consider storing images with the articles 

### ISSUE THREAD

**Issue by tobie** [unlockopen/www.unlockopen.com-v4#32]
See [article](https://gfscott.com/blog/eleventy-img-without-central-image-directory/).

**Comment by tobie** [comment]
Could you estimate how much time setting that up would actually take?

**Comment by madrilene** [comment]
Maybe an hour? 

I'd do that:

Store images and .md in directories by the same name, like
```
├── developers-apetite
│   ├── developers-appetite.jpg
│   ├── developers-appetite.jpg.yml
│   ├── developers-appetite.md
│   └── developers-appetite-square.jpg
```
referencing that image path in the article layout, defaulting to jpg (if the file ending differs, I'd set that in the front matter, I think that is most straight forward - if you have another idea let me know! 
The square image can then be referenced as well for the og-images.njk. 

So a front matter that differs from the jpg-standard would look like:

```
---
title: Behold second-order consequences!
date: 2019-03-05
image:
  extension: ".png"
  caption: "Alexandria Ocasio-Cortez's unique approach to fundraising also allows her to spend more time supporting fellow democrat candidtes like Kerri Evelyn Harris pictured here."
lede: "Alexandria Ocasio-Cortez's unique approach to fundraising not only sets her apart in Congress but also highlights the unexpected benefits of second-order consequences—a concept that proves equally transformative in the realm of open source software, where the true value lies beyond the code itself."
---
```

I'd also edit `image-metadata-index.js` so it takes the new dir` into consideration. I would still keep the general assets/images folder for other images.
